export const INVENTORY_LIST_REQUEST = 'INVENTORY_LIST_REQUEST'
export const INVENTORY_LIST_SUCCESS = 'INVENTORY_LIST_SUCCESS'
export const INVENTORY_LIST_FAIL = 'INVENTORY_LIST_FAIL'

export const INVENTORY_DETAILS_REQUEST = 'INVENTORY_DETAILS_REQUEST'
export const INVENTORY_DETAILS_SUCCESS = 'INVENTORY_DETAILS_SUCCESS'
export const INVENTORY_DETAILS_FAIL = 'INVENTORY_DETAILS_FAIL'
